### ISSUE TITLE
Reportes de fallos y actividades no realizadas 

### ISSUE THREAD

**Issue by juana0126** [DavidMontoya06/TA_08#2]
Tuvimos dificultad al intentar añadir imágenes al sitio web, era un fallo con el formato y la forma en la que estábamos subiendo el archivo a Replit. El problema ya está solucionado. ( convertimos el formato jpg en .png y subimos la imagen como nuevo archivo en Replit, con el fin de que se cree un código para la imagen y poder codificar para agregarla en el sitio web)

**Comment by DavidMontoya06** [comment]
Problema ya solucionado
