### ISSUE TITLE
Reporte de fallo

### ISSUE THREAD

**Issue by juana0126** [DavidMontoya06/TA_08#3]
Ya las imágenes están subidas en el Replit pero al codificar para agregar las imágenes al sitio web no se pueden ver las imágenes en la pagina web y el replit no muestra que posible error haya.

**Comment by DavidMontoya06** [comment]
Aprendimos que la librería que estamos utilizando (flask) es un poco "resabiada" y no deja meter las imágenes de la forma normal que es señalando la carpeta / y redirigiéndonos a la imagen como tal, entonces buscando nuevas formas de hacerlo nos enteramos que con "{{ url_for('static', filename='imagenes/nombre_de_la_imagen.png') }}" y así de manera fácil y eficiente podemos poner las imágenes guardadas en la carpeta imágenes dentro de la carpeta status
