### ISSUE TITLE
Reporte de fallo con la Base de datos.

### ISSUE THREAD

**Issue by juana0126** [DavidMontoya06/TA_08#4]
Tenemos un problema al crear la base de datos en Replit, consiste en que la librería que intentamos usar no se ejecuta al codificar "import" y por ende no lee el lenguaje al crear una File con este formato "database.db",creemos que no funciona porque estaos usando como libreria a Flask en la File principal "UMB.py" y por ello no ejecuta la otra librería. No pudimos crearla ppara el informe 05 pero el profesor nos paso unos tutoriales que esperamos que nos ayude con el problema, y cumplir con la base de datos para el informe 06.

**Comment by DavidMontoya06** [comment]
Ya volvimos a intentar y todo está correctamente con la base de datos
